FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y python3 python3-pip

# install numpy
RUN pip3 install numpy

# Add the code for the "install torch torchvision" container here!!!


WORKDIR /work

# Add the code for the "copy train.py" container here!!!
